# Site settings
title: Perry'S Blog
header-img: img/home-bg.jpg
email: 405401774@qq.com
copyright_name: Wang Perry
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "https://wpfcrazy.github.io"
twitter_username: 
github_username:  wpfcrazy
facebook_username:  
email_username:  405401774@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
